-- Seed data for the public.shows table
-- This populates the DB with the initial shows matching the schema

INSERT INTO public.shows (
  name,
  year,
  min_age,
  max_age,
  episode_minutes,
  genres,
  platforms,
  rating,
  narrative_pace,
  violence,
  language,
  educational_potential,
  addiction_risk,
  sleep_impact,
  attention_effect,
  analysis
) VALUES
(
  'Daniel Tigre',
  NULL,
  2,
  6,
  12,
  ARRAY['educativo'],
  ARRAY['YouTube', 'Netflix'],
  9,
  'lento',
  'nao',
  'apropriada',
  'alto',
  'baixo',
  'baixo',
  'positivo',
  'Ritmo previsível, linguagem clara e temas de regulação emocional. Bom para co-assistência e conversas sobre rotina.'
),
(
  'Word Party',
  NULL,
  3,
  6,
  12,
  ARRAY['educativo', 'linguagem'],
  ARRAY['Netflix'],
  8,
  'normal',
  'nao',
  'apropriada',
  'alto',
  'baixo',
  'baixo',
  'positivo',
  'Foco em vocabulário e repetição positiva. Estímulo moderado e boa estrutura de episódio.'
),
(
  'Octonautas',
  NULL,
  4,
  8,
  12,
  ARRAY['aventura', 'educativo'],
  ARRAY['Netflix'],
  8,
  'normal',
  'implicito',
  'apropriada',
  'medio',
  'medio',
  'medio',
  'neutro',
  'Aventura com aprendizado, mas pode acelerar dependendo do episódio. Bom com moderação e pausas.'
),
(
  'Homem-Aranha (heróis)',
  NULL,
  6,
  12,
  22,
  ARRAY['aventura', 'herois'],
  ARRAY['Disney+'],
  6,
  'acelerado',
  'implicito',
  'apropriada',
  'baixo',
  'medio',
  'medio',
  'neutro',
  'Ação e ritmo alto. Pode funcionar com moderação, preferencialmente longe do sono e com co-assistência.'
),
(
  'Rapunzel',
  2010,
  6,
  12,
  100,
  ARRAY['filme', 'fantasia'],
  ARRAY['Disney+'],
  7,
  'normal',
  'implicito',
  'apropriada',
  'medio',
  'baixo',
  'medio',
  'neutro',
  'Narrativa mais longa e cenas que podem ser intensas para os menores. Melhor com supervisão e pausas.'
),
(
  'Séries muito aceleradas',
  NULL,
  0,
  12,
  NULL,
  ARRAY['curtas', 'estimulacao'],
  ARRAY['YouTube'],
  2,
  'acelerado',
  'nao',
  'questionavel',
  'baixo',
  'alto',
  'alto',
  'negativo',
  'Trocas rápidas e estímulo constante aumentam risco de irritação ao desligar e piora de atenção, especialmente em crianças menores.'
),
(
  'Séries com conteúdo inapropriado',
  NULL,
  16,
  99,
  NULL,
  ARRAY['adulto'],
  ARRAY['Streaming'],
  0,
  'normal',
  'sim',
  'inapropriada',
  'baixo',
  'alto',
  'alto',
  'negativo',
  'Conteúdo para adultos não é adequado para crianças.'
);
